version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "${NGINX_HOST_PORT}:80"
      - "${NGINX_HOST_PORT_HTTPS}:443"
    environment:
      FRONT_IP:
      FRONT_PORT:
      BACK_IP:
      BACK_PORT:
      NGINX_HOST_PORT_HTTPS:
      NGINX_HOST_PORT:
      TZ:
    command:
      - /bin/bash
      - -c
      - "envsubst \
        '                                          \
         $$FRONT_IP $$FRONT_PORT $$BACK_IP $$BACK_PORT \
         $$NGINX_HOST_PORT_HTTPS $$NGINX_HOST_PORT                   \
        '                                          \
        < /etc/nginx/conf.d/mysite.template        \
        > /etc/nginx/conf.d/default.conf           \
        && exec nginx -g 'daemon off;'"
    depends_on:
      - vue
      - platform
      - rmt

  front:
    image: dragee/front:v1.0.0
    ports:
      - "${FRONT_HOST_PORT}:${FRONT_PORT}"
    environment:
      TZ:

  # 后端
  back:
    image: dragee/back:v1.0.0
    ports:
      - "${PLATFORM_HOST_PORT}:8080"
    environment:
      TZ:
    volumes:
      - ../upload:/tmp/upload
    command:
      - "--spring.profiles.active=${PLATFORM_ENV}"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      TZ:
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ALLOW_INVALID_DATES

 