spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        enable: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.36.1.51:5004/fms_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: example
      postgis:
        enable: true
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://121.36.1.51:5006/fms_db
        username: postgres
        password: example
  redis:
    host: 121.36.1.51
    port: 5005
    database: 0
    password: webull

webull:
  mapUploadPath: /tmp/upload
  configCenterAddr: https://config.agro-robot.net/api
  accessKeyId: LTAIUeRkwSM8DD9H
  accessKeySecret: wsBmAuG2cbyyBKsO17HwB2YrQQlnX5
  signName: 悟牛智能
  mqtt:
    # url: tcp://192.168.0.85:1883
    url: tcp://121.36.1.51:4006
    username: guest
    password: guest
    clientId: paltfrom-${random.int}
    completionTimeout: 3000
    keepAliveInterval: 2000
  swagger:
    enable: true